controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    gripper_controller:
      type: position_controllers/GripperActionController


gripper_controller:
  ros__parameters:
    action_monitor_rate: 500.0
    allow_stalling: false
    goal_tolerance: 0.002
    joint: wsg50_joint
    max_effort: 0.0
